#include QMK_KEYBOARD_H

#define BASE 0
#define NUMBER 1
#define FUNCTION 2
#define MACRO 3
#define SYSTEM 4

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [BASE] = LAYOUT_ortho_4x12(
        KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
        KC_ESC, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT,
        OSM(MOD_LSFT), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, OSM(MOD_RSFT),
        OSL(3), OSM(MOD_LCTL), OSM(MOD_LALT), OSL(2), OSL(1), KC_SPC, KC_ENT, OSL(1), OSL(2), OSL(4), OSM(MOD_RGUI), OSL(3)
    ),

    [NUMBER] = LAYOUT_ortho_4x12(
        KC_TILD, KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_NO, KC_PLUS, KC_P7, KC_P8, KC_P9, KC_EQL, KC_DEL,
        KC_GRV, KC_NO, KC_PERC, KC_CIRC, KC_AMPR, KC_NO, KC_MINS, KC_P4, KC_P5, KC_P6, KC_UNDS, KC_BSLS,
        KC_NO, KC_NO, KC_ASTR, KC_NO, KC_NO, KC_NO, KC_NO, KC_P1, KC_P2, KC_P3, KC_NO, KC_NO,
        KC_LCBR, KC_LPRN, KC_LBRC, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_TRNS, KC_P0, KC_RBRC, KC_RPRN, KC_RCBR
    ),

    [FUNCTION] = LAYOUT_ortho_4x12(
        KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_NO, KC_MUTE, KC_VOLD, KC_VOLU, KC_BRID, KC_BRIU, KC_NO,
        KC_NO, KC_F5, KC_F6, KC_F7, KC_F8, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO,
        KC_NO, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_MPLY, KC_MRWD, KC_MFFD, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO
    ),

    [MACRO] = LAYOUT_ortho_4x12(
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS
    ),

    [SYSTEM] = LAYOUT_ortho_4x12(
        DEBUG, RESET, KC_NO, KC_NO, KC_NO, KC_NO, KC_PWR, KC_SLEP, KC_WAKE, KC_NO, KC_NO, KC_NO,
        EEP_RST, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO
    )
};
