#include QMK_KEYBOARD_H
#include "mluds.h"

#define _BASE 0
#define _NUM 1
#define _FUN 2
#define _MAC 3
#define _SYS 4

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [_BASE] = LAYOUT_ortho_4x12(
        KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_ENT,
        KC_ESC, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT,
        OSM(MOD_LSFT), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, OSM(MOD_RSFT),
        OSL(_MAC), OSM(MOD_LCTL), OSM(MOD_LALT), OSL(_FUN), OSL(_NUM), KC_SPC, KC_BSPC, OSL(_NUM), OSL(_FUN), OSL(_SYS), OSM(MOD_RGUI), OSL(_MAC)
    ),

    [_NUM] = LAYOUT_ortho_4x12(
        KC_NO, KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_PERC, KC_PLUS, KC_P7, KC_P8, KC_P9, KC_EQL, KC_NO,
        KC_LCBR, KC_LBRC, KC_CIRC, KC_AMPR, KC_ASTR, KC_PIPE, KC_MINS, KC_P4, KC_P5, KC_P6, KC_RBRC, KC_RCBR,
        KC_NO, KC_NO, X(FACE), X(LAUGH), X(THINK), X(THUMB), KC_NO, KC_P1, KC_P2, KC_P3, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_LPRN, KC_RPRN, KC_TRNS, KC_P0, KC_NO, KC_NO, KC_NO
    ),

    [_FUN] = LAYOUT_ortho_4x12(
        KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, CAD, KC_MUTE, KC_VOLD, KC_VOLU, KC_BRID, KC_BRIU, KC_NO,
        KC_NO, KC_F5, KC_F6, KC_F7, KC_F8, SKYPE_MUTE, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO,
        KC_NO, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_MPLY, KC_MRWD, KC_MFFD, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO
    ),

    [_MAC] = LAYOUT_ortho_4x12(
        KC_NO, VIM_QUIT, VIM_WRITE, TMUX_SPLIT_MOVE, TMUX_SPLIT_V, TMUX_SPLIT_H, KC_NO, TMUX_TAB_LEFT, TMUX_TAB_RIGHT, TMUX_TAB_NEW, TMUX_TAB_DEL, KC_NO,
        KC_NO, GIT_ADD, GIT_COMMIT, GIT_DIFF, GIT_STAT, KC_NO, VIM_WNDW_LEFT, VIM_WNDW_DOWN, VIM_WNDW_UP, VIM_WNDW_RIGHT, VIM_WNDW_EQ, KC_NO,
        KC_NO, GIT_PULL, GIT_PUSH, GIT_FETCH, TMUX_PASTE, KC_NO, KC_NO, VIM_TAB_LEFT, VIM_TAB_RIGHT, VIM_TAB_NEW, VIM_TAB_DEL, KC_NO,
        KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS
    ),

    [_SYS] = LAYOUT_ortho_4x12(
        DEBUG, RESET, KC_NO, KC_NO, KC_NO, KC_NO, KC_PWR, KC_SLEP, KC_WAKE, KC_NO, KC_NO, KC_NO,
        EEP_RST, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO
    ),
};
